"""Add Review Model

Revision ID: 758189b2d5ad
Revises: ab29dcf7f782
Create Date: 2023-08-22 12:51:32.199159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758189b2d5ad'
down_revision = 'ab29dcf7f782'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
